# Generated by Django 5.1.1 on 2024-10-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, choices=[('CE', 'Central'), ('PR', 'Punta Receptor'), ('AR', 'Armador'), ('OP', 'Opuesto'), ('LI', 'Líbero')], max_length=2, null=True),
        ),
    ]
