# Generated by Django 5.1.1 on 2024-10-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_holding',
            field=models.BooleanField(default=False),
        ),
    ]
