# Generated by Django 5.1.1 on 2024-10-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_player_is_holding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='avatar_url',
            new_name='avatar',
        ),
        migrations.AddField(
            model_name='team',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True),
        ),
    ]
