# Generated by Django 5.1.1 on 2024-10-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_matches', models.IntegerField(default=0)),
                ('total_teams', models.IntegerField(default=0)),
                ('top_scorer_name', models.CharField(blank=True, max_length=100)),
                ('top_scorer_score', models.IntegerField(default=0)),
                ('most_wins_team', models.CharField(blank=True, max_length=100)),
                ('most_wins_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
