# Generated by Django 5.1.1 on 2024-10-11 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_match_duration_match_start_time'),
        ('teams', '0002_player_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerperformance',
            name='blocks',
        ),
        migrations.RemoveField(
            model_name='playerperformance',
            name='digs',
        ),
        migrations.AddField(
            model_name='match',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='match_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='match',
            name='total_spectators',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='block_points',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='errors',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_performances', to='matches.set'),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='spike_points',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerperformance',
            name='aces',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='PointEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('point_type', models.CharField(blank=True, choices=[('SPK', 'Punto por Remate'), ('BLK', 'Punto por Bloqueo'), ('ACE', 'Punto por Saque Directo'), ('ERR', 'Error del Oponente')], max_length=3, null=True)),
                ('home_score_after', models.PositiveIntegerField(blank=True, null=True)),
                ('away_score_after', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_events', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.player')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_events', to='matches.set')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
    ]
