# Generated by Django 5.1.1 on 2024-10-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_remove_playerperformance_blocks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerperformance',
            name='digs',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='total_blocks',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
