# Generated by Django 5.1.1 on 2024-10-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_playerperformance_digs_and_more'),
        ('teams', '0002_player_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerperformance',
            name='aces',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerperformance',
            name='block_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerperformance',
            name='digs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerperformance',
            name='errors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerperformance',
            name='spike_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerperformance',
            name='total_blocks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='playerperformance',
            unique_together={('player', 'match', 'set')},
        ),
    ]
