# Generated by Django 5.1.1 on 2024-10-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_alter_playerperformance_aces_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='is_finished',
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Próximamente'), ('live', 'En Vivo'), ('finished', 'Finalizado'), ('suspended', 'Suspendido'), ('rescheduled', 'Reprogramado')], default='upcoming', max_length=20),
        ),
    ]
