# Generated by Django 5.1.1 on 2024-10-16 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_remove_match_is_finished_match_status'),
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='current_weather',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_match', to='weather.weather'),
        ),
    ]
