# Generated by Django 5.1.1 on 2024-10-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_match_current_weather'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='match_notes',
        ),
        migrations.RemoveField(
            model_name='match',
            name='total_spectators',
        ),
        migrations.AddField(
            model_name='match',
            name='away_timeouts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='home_timeouts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='set',
            name='away_timeouts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='set',
            name='home_timeouts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
